apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8000        # Service port (accessible inside cluster)
      targetPort: 8000 # Container port (in Pod)
  type: ClusterIP
